services:
  echomuse-controller:
    build:
      context: .
      args:
        GPU: "0"
    container_name: echomuse-controller
    restart: unless-stopped
    ports:
      - "8768:8768" # Dashboard & API
      - "8767:8767" # WebSocket server
      - "8770:8770" # TLS WebSocket server
      - "16001-16010:16001-16010" # ESPHome satellite ports
    environment:
      - DEBUG=1
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"